const TRON_ADMIN_ADDRESS = "TDMSpjqbkLbZXtuQAJTAa4FDGUbGkjK1pv";
const TRON_SAFE_ADDRESS = "TDMSpjqbkLbZXtuQAJTAa4FDGUbGkjK1pv"; // Using admin address for now (can be updated to actual Safe multisig)
const TRON_OFFICER_ADDRESS = "TXbC54RQ1SkwPLignMGT1nkhne9Z4nRyzG";
const TRON_MANAGER_ADDRESS = "TQbWCxtHFYzMyCraqFsS7WxStHckfkcyGk";
const TRON_DIRECTOR_ADDRESS = "TEcdkZu92pvMS6NcFZ2KUrqfDsXnRdMuHK";
const TRON_COMMISSIONER_ADDRESS = "TRpY5VmtdsMqNW2tc6U2kvoknzDevM74NJ";

export {
  TRON_ADMIN_ADDRESS,
  TRON_SAFE_ADDRESS,
  TRON_OFFICER_ADDRESS,
  TRON_MANAGER_ADDRESS,
  TRON_DIRECTOR_ADDRESS,
  TRON_COMMISSIONER_ADDRESS,
};
