const ADMIN_ADDRESS = "TEF4ySTQ5RPct3L77iotiw88Em9R3TPxTK";
const OFFICER_ADDRESS = "TSRx8PDjxidAfEk4kE99nn5j5MtswQ7QLf";
const MANAGER_ADDRESS = "TVHoZddRzQJB2DPaHXqAiLnSeyQ2YKQQBE";
const DIRECTOR_ADDRESS = "TKKxJwzTzUMEQzZX3KLDBgK6zzFeDRpGWA";
const COMMISSIONER_ADDRESS = "TKKxJwzTzUMEQzZX3KLDBgK6zzFeDRpGWA";
const TRON_ADMIN_ADDRESS = "TEF4ySTQ5RPct3L77iotiw88Em9R3TPxTK";
const TRON_OFFICER_ADDRESS = "TSRx8PDjxidAfEk4kE99nn5j5MtswQ7QLf";
const TRON_MANAGER_ADDRESS = "TVHoZddRzQJB2DPaHXqAiLnSeyQ2YKQQBE";
const TRON_DIRECTOR_ADDRESS = "TAynASiigebcr5uS2owvKE5VgXtKZ5GTZc";
const TRON_COMMISSIONER_ADDRESS = "TNVBrQ3LzbaKNZjsK3HWRCQYmohHe4Rqy6";
const TRON_DEPOSITORY_ADDRESS = "TMUg5HNDGjp1JjuworWPck6i762NCuCdmj";

export {
  ADMIN_ADDRESS,
  OFFICER_ADDRESS,
  MANAGER_ADDRESS,
  DIRECTOR_ADDRESS,
  COMMISSIONER_ADDRESS,
  TRON_ADMIN_ADDRESS,
  TRON_OFFICER_ADDRESS,
  TRON_MANAGER_ADDRESS,
  TRON_DIRECTOR_ADDRESS,
  TRON_COMMISSIONER_ADDRESS,
  TRON_DEPOSITORY_ADDRESS,
};
